//ACTIONS TYPES
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
//MESSAGE TYPES 
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE  = "CLEAR_MESSAGE";
//actions type for project
export const  PROJECT_CREATED = "PROJECT_CREATED";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const  PROJECT_UPDATED = "PROJECT_UPDATED";