//ACTIONS TYPES
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
//MESSAGE TYPES
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
//actions type for project
export const GET_PROJECT_BY_ID_SUCCESS = "GET_PROJECT_BY_ID_SUCCESS";
export const GET_PROJECT_BY_ID_FAILURE = "GET_PROJECT_BY_ID_FAILURE";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const ADD_PROJECT_REQUEST = "ADD_PROJECT_REQUEST";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAILURE = "ADD_PROJECT_FAILURE";
export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";
export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";
////
export const GET_MEMBER_SUCCESS = "GET_MEMBER_SUCCESS";
export const GET_MEMBER_FAILURE = "GET_MEMBER_FAILURE";

//
export const CREATE_CHATROOM_REQUEST = 'CREATE_CHATROOM_REQUEST';
export const CREATE_CHATROOM_SUCCESS = 'CREATE_CHATROOM_SUCCESS';
export const CREATE_CHATROOM_FAILURE = 'CREATE_CHATROOM_FAILURE';

export const GET_ALL_CHATROOMS_REQUEST = 'GET_ALL_CHATROOMS_REQUEST';
export const GET_ALL_CHATROOMS_SUCCESS = 'GET_ALL_CHATROOMS_SUCCESS';
export const GET_ALL_CHATROOMS_FAILURE = 'GET_ALL_CHATROOMS_FAILURE';

export const GET_CHATROOM_BY_ID_REQUEST = 'GET_CHATROOM_BY_ID_REQUEST';
export const GET_CHATROOM_BY_ID_SUCCESS = 'GET_CHATROOM_BY_ID_SUCCESS';
export const GET_CHATROOM_BY_ID_FAILURE = 'GET_CHATROOM_BY_ID_FAILURE';

export const ADD_MESSAGE_TO_CHATROOM_REQUEST = 'ADD_MESSAGE_TO_CHATROOM_REQUEST';
export const ADD_MESSAGE_TO_CHATROOM_SUCCESS = 'ADD_MESSAGE_TO_CHATROOM_SUCCESS';
export const ADD_MESSAGE_TO_CHATROOM_FAILURE = 'ADD_MESSAGE_TO_CHATROOM_FAILURE';
